## AI Lab 09: Pandas
Task 1: Data Cleaning
Dataset: create dataset students.csv (columns: Name, Age, Department, Marks)
Instructions:
1. Load the dataset into Pandas.
2. Identify and fill missing values using mean/median.
3. Remove any duplicate rows.
4. Rename the Marks column to Score.
5. Save the cleaned data as cleaned_students.csv.

In [3]:
## Importing the Pandas Library
import pandas as pd

In [5]:
# loading the dataset named student.csv
df = pd.read_csv("students.csv")
df

     Name   Age Department  Marks
0     Ali  23.0         CS   85.0
1    Sara  25.0         IT   90.0
2    John  22.0         CS   78.0
3  Ayesha  24.0         EE   88.0
4   Bilal   NaN         CS   75.0
5    Sami  23.0         IT    NaN
6     Ali  23.0         CS   85.0

In [7]:
# Identifying and fill the missing values
df.isnull().sum()

Name          0
Age           1
Department    0
Marks         1
dtype: int64

In [17]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
# As the age is continues so we use the mean to fill in the age
df

     Name        Age Department  Marks
0     Ali  23.000000         CS   85.0
1    Sara  25.000000         IT   90.0
2    John  22.000000         CS   78.0
3  Ayesha  24.000000         EE   88.0
4   Bilal  23.333333         CS   75.0
5    Sami  23.000000         IT    NaN
6     Ali  23.000000         CS   85.0

In [21]:
# Removing duplicate rows
# First checking the duplicate rows
df.duplicated().sum()

1

In [25]:
# As the duplicate exists so removing them
df = df.drop_duplicates()
df

     Name        Age Department  Marks
0     Ali  23.000000         CS   85.0
1    Sara  25.000000         IT   90.0
2    John  22.000000         CS   78.0
3  Ayesha  24.000000         EE   88.0
4   Bilal  23.333333         CS   75.0
5    Sami  23.000000         IT    NaN

In [27]:
df = df.rename(columns={"Marks" : "Score"})
df

     Name        Age Department  Score
0     Ali  23.000000         CS   85.0
1    Sara  25.000000         IT   90.0
2    John  22.000000         CS   78.0
3  Ayesha  24.000000         EE   88.0
4   Bilal  23.333333         CS   75.0
5    Sami  23.000000         IT    NaN

In [29]:
# Save cleaned dataset
df.to_csv("cleaned_students.csv", index=False)

Task 2: Statistical Analysis
Using the cleaned dataset:
1. Find mean, median, max, min, and standard deviation of Score.
2. Group students by Department and calculate average score per department.
3. Sort students by Score (descending order).

In [43]:
# Finding Mean, Median, Max, Min and Standard Deviation(SD) of Score
import pandas as pd
df = pd.read_csv("cleaned_students.csv")

mean_score = df["Score"].mean()
median_score = df["Score"].median()
max_score = df["Score"].max()
min_score = df["Score"].min()
std_score = df["Score"].std()

print("The mean of the score is: ",mean_score)
print("The median of the score is:" ,median_score)
print("The max of the score is: ", max_score)
print("The min of the score is:" ,min_score)
print("The std of the score is:" ,std_score)

The mean of the score is:  83.2
The median of the score is: 85.0
The max of the score is:  90.0
The min of the score is: 75.0
The std of the score is: 6.457553716385176

In [45]:
# Group by department and calculate average score
df.groupby("Department")["Score"].mean()

Department
CS    79.333333
EE    88.000000
IT    90.000000
Name: Score, dtype: float64

In [47]:
# Sort Students by their score in descending order
df_sorted = df.sort_values(by="Score", ascending = False)
df_sorted

     Name        Age Department  Score
1    Sara  25.000000         IT   90.0
3  Ayesha  24.000000         EE   88.0
0     Ali  23.000000         CS   85.0
2    John  22.000000         CS   78.0
4   Bilal  23.333333         CS   75.0
5    Sami  23.000000         IT    NaN

## Task 3: Mini Project — Student Performance Data
1. Create a DataFrame manually for 5 students having Name, Age, Department, and Marks.
2. Display:
 • Top 3 rows
 • Specific columns (Name, Marks)
 • Students with Marks > 80
3. Generate a statistical summary using describe().

In [52]:
import pandas as pd
data = {
    "Name" : ["Ali","Sara", "Ahmad", "Ayesha", "Bilal"],
    "Age" : [23,25,22,24,21],
    "Department": ["CS","IT", "CS", "EE", "CS"],
    "Marks" : [85,90,100,88,28]
    
}
students = pd.DataFrame(data)
students

     Name  Age Department  Marks
0     Ali   23         CS     85
1    Sara   25         IT     90
2   Ahmad   22         CS    100
3  Ayesha   24         EE     88
4   Bilal   21         CS     28

In [56]:
# Dispalying top three rows
students.head(3)

    Name  Age Department  Marks
0    Ali   23         CS     85
1   Sara   25         IT     90
2  Ahmad   22         CS    100

In [58]:
# Displaying specific columns (Name, Marks)
students[["Name", "Marks"]]

     Name  Marks
0     Ali     85
1    Sara     90
2   Ahmad    100
3  Ayesha     88
4   Bilal     28

In [62]:
# Displaying students with Marks > 80
students[students["Marks"] > 80]

     Name  Age Department  Marks
0     Ali   23         CS     85
1    Sara   25         IT     90
2   Ahmad   22         CS    100
3  Ayesha   24         EE     88

In [70]:
# Generate statistical summary
students.describe()

             Age      Marks
count   5.000000    5.00000
mean   23.000000   78.20000
std     1.581139   28.62167
min    21.000000   28.00000
25%    22.000000   85.00000
50%    23.000000   88.00000
75%    24.000000   90.00000
max    25.000000  100.00000